---
title: "Fit Household Model"
---


## Summary

This notebook contains code to model to predict the number of household contacts. 


## Library function + helper code  

```{r}
## library here package 
library(here)
## Load helper functions and library all packages used for analysis 
source(here("code", "models", "mrp", "helpers.R"))
```

This data file was cleaned and prep'd in another notebook (`00_data_prep.Rmd`). 

```{r}
## prepared for model  
df_formodel <- read_rds(here('data', 'mrp', 'input', 'df_formodel_waves1_6.rds')) 

## top code total number of reported contacts at 30 
top_code <- function(x) {
  x <- case_when(
    x > 30 ~ 30,
    TRUE ~ x
  )
}

## topcode data.frame 
df_formodel_topcode <- df_formodel %>%
  mutate(across(c(starts_with("alter_age")), top_code)) %>% 
  filter(hhsize != "1") 
```


Run final household model for paper 

```{r}
## run model 
hh_model <- brm(
  formula = mvbind(alter_age_0_18_hh, alter_age_18_25_hh, alter_age_25_35_hh, alter_age_35_45_hh, alter_age_45_55_hh, alter_age_55_65_hh, alter_age_65_100_hh) ~ 
    agecat +
    gender +
    hhsize + 
    race + 
    agecat:gender + 
    (1 | state),
  #poly(day_std, 3) + ## national polynomial trend 
  # (poly(day_std, 3) | state), ## state level pooled polynomial trend 
  family = 'negbinomial',
  inits = 0,
  data = df_formodel_topcode,
  chains = 4,
  cores = 16,
  backend = "cmdstanr",
  threads = threading(4),
  #  control = list(adapt_delta = 0.9), 
  iter = 4000)

## write out model 
write_rds(hh_model, file = here('data', 'mrp', 'models', 'hh_model.rds'))
```

