---
title: "Fit MRT Models with Mobility Data"
author: Casey Breen
---

## Summary

This notebook contains code to fit two models: one model to estimate non-household contacts and one to model to estimate household contacts.

```{r}
## library here package 
library(here)
## Load helper functions and library all packages used for analysis 
source(here("code", "helpers.R"))
```


```{r}
## prepared for model  
df_formodel <- read_rds(here('data', 'input', 'bics_data_waves_1-6.rds')) 

## top code total number of reported contacts at 30 
top_code <- function(x) {
  x <- case_when(
    x > 30 ~ 30,
    TRUE ~ x
  )
}

## topcode data.frame 
df_formodel_topcode <- df_formodel %>%
  mutate(across(c(starts_with("alter_age")), top_code))
```


## read in data for model 

```{r}
waves <- c(2:5)
results <- list()

for (i in waves){
  
  ## create test data 
  test_wave <- df_formodel_topcode %>% 
    filter(wave == i)
  
  ## read in models 
  model_mobility <- read_rds(file = here('data', 'models', glue('nonhh_model_holdout_wave{i}.rds')))
  model_baseline <- read_rds(file = here('data', 'models', glue('nonhh_model_no_mobility_holdout_wave{i}.rds')))
  
  ## predictions for mobility data 
  predicted_draws_mobility <- add_predicted_draws(newdata = test_wave, object = model_mobility, ndraws = 3000, allow_new_levels = T) %>%
    mutate(numcc_predict = .prediction) %>% 
    ungroup() %>% 
    select(rid, state, agecat, gender, hhsize, race, weekday, day_std, .draw, numcc_predict, .category)
  
  
  ## summarize mobility data predictions 
  predictions_mobility <- predicted_draws_mobility %>% 
    group_by(rid, category = .category) %>% 
    summarize(predict_mobility = mean(numcc_predict))
  
  rm(predicted_draws_mobility)
  
  ## predicted draws baseline 
  predicted_draws_baseline <- add_predicted_draws(newdata = test_wave, object = model_baseline, ndraws = 3000, allow_new_levels = T) %>%
    mutate(numcc_predict = .prediction) %>% 
    ungroup() %>% 
    select(rid, state, agecat, gender, hhsize, race, weekday, day_std, .draw, numcc_predict, .category)
  
  ## summarize mobility data predictions 
  predictions_baseline <- predicted_draws_baseline %>% 
    group_by(rid, category = .category) %>% 
    summarize(predict_baseline = mean(numcc_predict))
  
  rm(predicted_draws_baseline)
  
  ## combine predictions into one data.frame 
  make_predictions <- predictions_mobility %>% 
    left_join(predictions_baseline, by = c("rid", "category"))
  
  ## combine into one data.frame 
  test_wave_long <- test_wave %>% 
    select(rid, alterage018 = alter_age_0_18,
           alterage1825 = alter_age_18_25,
           alterage2535 = alter_age_25_35,
           alterage3545 = alter_age_35_45,
           alterage4555 = alter_age_45_55,
           alterage5565 = alter_age_55_65,
           alterage65100 = alter_age_65_100) %>% 
    pivot_longer(-rid) %>% 
    rename(category = name) %>% 
    left_join(make_predictions)
  
  ## calculate test wave 
  mse_error <- test_wave_long %>% 
    mutate(error_mobility = (value - predict_mobility)^2, 
           error_baseline = (value - predict_baseline)^2) %>% 
    summarize(mse_baseline = mean(error_baseline),
              mse_mobility = mean(error_mobility),
              mean_diff = mean(error_baseline - error_mobility),
              se_diff = sd(error_baseline - error_mobility)/sqrt(n())) %>% 
    mutate(t_stat = mean_diff/se_diff,
           wave = i)
  
  ## add mse to results 
  results[[i]] <- mse_error 
  
  ## print
  cat("Finished with wave ", i)
  
  gc()
  
}


bind_rows(results) %>% 
  knitr::kable(format = "latex", digits = 2)

```


```{r}
bind_rows(results) %>% 
  ggplot(aes(x = wave, y = mean_diff, ymin = mean_diff - 2*se_diff, ymax = mean_diff + 2*se_diff)) + 
  geom_pointrange() + 
  theme_cowplot() +
  geom_hline(yintercept = 0, linetype = "dashed") + 
  labs(y = "MSE Baseline - MSE Mobility")
```




```{r}
## Run main model non-hh model for paper 

df_formodel_topcode <- df_formodel_topcode %>% 
  filter(wave != 6)

## mobility + monthly national cubic + state-level hierarchical cubic term 
## Total execution time: 5346.0 seconds.
nonhh_model <- brm(
  formula = mvbind(alter_age_0_18, alter_age_18_25, alter_age_25_35, alter_age_35_45, alter_age_45_55, alter_age_55_65, alter_age_65_100) ~ 
    agecat +
    gender +
    hhsize + 
    race + 
    weekday + 
    agecat:gender + 
    rolling_pca_3wks + ## mobility data 
    poly(day_std, 3) + ## national polynomial trend 
    (poly(day_std, 3) | state), ## state level pooled polynomial trend 
  family = 'negbinomial',
  inits = 0,
  data = df_formodel_topcode,
  chains = 4,
  cores = 16,
  iter = 4000)

write_rds(nonhh_model, file = here('data', 'models', 'nonhh_model_holdout_wave6.rds'))

## Run main model non-hh without mobility data 


## mobility + monthly national cubic + state-level hierarchical cubic term 
## Total execution time: 5346.0 seconds.
nonhh_model_no_mobility <- brm(
  formula = mvbind(alter_age_0_18, alter_age_18_25, alter_age_25_35, alter_age_35_45, alter_age_45_55, alter_age_55_65, alter_age_65_100) ~ 
    agecat +
    gender +
    hhsize + 
    race + 
    weekday + 
    agecat:gender + 
    poly(day_std, 3) + ## national polynomial trend 
    (poly(day_std, 3) | state), ## state level pooled polynomial trend 
  family = 'negbinomial',
  inits = 0,
  data = df_formodel_topcode,
  chains = 4,
  cores = 16,
  iter = 4000)

write_rds(nonhh_model_no_mobility, file = here('data', 'models', 'nonhh_model_no_mobility_holdout_wave6.rds'))
```


